#!/usr/bin/env python3
"""Push the high‑level view (buyers + shopping list) into GoHighLevel.

The script reads ``data/high_level_view.json`` generated by the Playwright
pipeline and creates or updates a contact for each buyer using the GHL contacts
API.  For every buyer we store the aggregated list of matched properties in a
custom field named ``shopping_list`` as a JSON‑encoded string – this allows the
list to be inspected later via GHL’s built‑in dashboards or automation
workflows.

Prerequisites
-------------
* Environment variables ``GHL_API_KEY`` and ``GHL_LOCATION_ID`` must be set (the
  same variables are used by ``ghl_automation_test.py``).  If they are not
  present the script will abort with a clear error message.
* The GHL account must have a custom field called ``shopping_list`` (type
  “Text”).  The field ID can be obtained from the GHL UI – replace the placeholder
  ``CUSTOM_FIELD_ID`` below with the actual field ID.
* ``requests`` is installed in the virtualenv (``pip install requests``).

Usage
-----
    source ~/.venv/bin/activate
    python push_to_ghl.py

The script is idempotent – it updates an existing contact when the email matches,
otherwise it creates a new one.
"""

import os
import json
import sys
from pathlib import Path
import requests

# ---------------------------------------------------------------------------
# Configuration – Private Integration Token (Bearer pit-…) via shared helper
# ---------------------------------------------------------------------------
_SKILL = Path("/home/keith/real_estate/.claude/skills/wholesale-demand-align/scripts")
if str(_SKILL) not in sys.path:
    sys.path.insert(0, str(_SKILL))

from dotenv import load_dotenv

load_dotenv("/home/keith/real_estate/.env")

from ghl_repository import (  # noqa: E402
    API_VERSION,
    BASE_URL as REPO_BASE_URL,
    USER_AGENT,
    authorization_bearer_pit,
    normalize_pit_token,
    GhlRepository,
)

# Use the host defined by the shared repository helper (services.leadconnectorhq.com).
BASE_URL = REPO_BASE_URL

GHL_API_KEY = normalize_pit_token(os.getenv("GHL_API_KEY") or "")
GHL_LOCATION_ID = (os.getenv("GHL_LOCATION_ID") or "").strip()
if not GHL_API_KEY or not GHL_LOCATION_ID:
    sys.stderr.write(
        "Error: GHL_API_KEY (pit-…) and GHL_LOCATION_ID must be set in the environment.\n"
    )
    sys.exit(1)

HEADERS = {
    "Authorization": authorization_bearer_pit(GHL_API_KEY),
    "Version": API_VERSION,
    "Accept": "application/json",
    "Content-Type": "application/json",
    "User-Agent": USER_AGENT,
}

# ---------------------------------------------------------------------------
# Helper: upsert a contact based on e‑mail address
# ---------------------------------------------------------------------------
def upsert_contact(buyer_key: str, buyer_data: dict, properties: list[dict]):
    """Create or update a GHL contact.

    ``buyer_key`` – a string used for logging (email or name).
    ``buyer_data`` – dictionary that may contain ``email``, ``first_name``,
        ``last_name`` and ``phone``.
    ``properties`` – list of property dicts that we store in a custom field.
    """
    email = buyer_data.get("email")
    if not email:
        # Skip entries without an email – GHL contacts are keyed by e‑mail.
        print(f"[skip] {buyer_key}: no e‑mail address – cannot upsert.")
        return

    # Prepare the payload.  The custom field ID must be replaced with the real one.
    CUSTOM_FIELD_ID = "cf_c67431ff70d6440fb529c2705792425f"  # ← replace with actual field ID from GHL
    # The v2 API expects `customFields` to be an **array** of objects with `fieldId`
    # and `value`.  We wrap the JSON‑encoded shopping‑list in that structure.
    payload = {
        "locationId": GHL_LOCATION_ID,
        "firstName": buyer_data.get("first_name", ""),
        "lastName": buyer_data.get("last_name", ""),
        "email": email,
        "phone": buyer_data.get("phone", ""),
        "customFields": [
            {
                "fieldId": CUSTOM_FIELD_ID,
                "value": json.dumps(properties, ensure_ascii=False),
            }
        ],
        # Optional tags – you can add a tag to identify pipeline contacts.
        "tags": ["buyer_shopping_list"],
    }

    # The v2 API’s upsert endpoint is POST /v2/contacts/upsert. It will create a
    # new contact if none exists or update the existing one based on the email address.
    # Therefore we skip any separate search step and directly POST the payload.
    # Use the shared repository client for a reliable upsert. It handles the
    # correct host, auth header, and request formatting.
    repo = GhlRepository()
    result = repo.upsert_contact(payload)
    if result.ok:
        print(f"[upserted] {buyer_key} (contact_id={result.contact_id})")
    else:
        print(f"[upsert error] {buyer_key}: {result.detail}")

# ---------------------------------------------------------------------------
# Main – load the high‑level JSON and push each buyer.
# ---------------------------------------------------------------------------
def main():
    # The JSON is generated by the Playwright pipeline and lives in the `data`
    # directory alongside this script (i.e. `<project>/data/high_level_view.json`).
    # Using `parents[1]` incorrectly pointed to `/home/keith/real_estate`.
    # Use the script's own directory (`parent`) to locate the correct path.
    high_level_path = Path(__file__).parent / "data" / "high_level_view.json"
    if not high_level_path.is_file():
        sys.stderr.write(f"Error: {high_level_path} not found. Run the pipeline first.\n")
        sys.exit(1)

    with open(high_level_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    shopping_list = data.get("shopping_list", {})
    if not shopping_list:
        print("No shopping‑list data found – nothing to push.")
        return

    for buyer_key, props in shopping_list.items():
        # Derive a minimal buyer data structure for the contact payload.
        # The key format is either an e‑mail address or "First Last".
        if "@" in buyer_key:
            buyer_data = {"email": buyer_key}
        else:
            parts = buyer_key.split()
            buyer_data = {
                "first_name": parts[0] if parts else "",
                "last_name": " ".join(parts[1:]) if len(parts) > 1 else "",
            }
        upsert_contact(buyer_key, buyer_data, props)

if __name__ == "__main__":
    main()
